name: "Sync Upstream"

on:
  schedule:
  - cron: '0 0 * * *'
  
jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    if: github.repository_owner != 'NixOS'
    strategy:
      max-parallel: 1
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch remotes
        id: remotes
        run: |
          git remote add upstream 'https://github.com/NixOS/nixpkgs.git'
          git fetch upstream master nixpkgs-unstable
          git fetch origin master more-branches
          behind=$(git rev-list --count origin/master...upstream/master)
          weekly=$(git fetch origin weekly && git log origin/weekly -n1 --format=%ct || echo 604800)
          monthly=$(git fetch origin monthly && git log origin/monthly -n1 --format=%ct || echo 2592000)
          let weekly-=604800 monthly-=2592000
          echo behind=$behind | tee -a $GITHUB_OUTPUT
          echo weekly=$weekly | tee -a $GITHUB_OUTPUT
          echo monthly=$monthly | tee -a $GITHUB_OUTPUT
          
      - name: Sync master
        if: steps.remotes.outputs.behind > 0
        run: |
          git -c checkout.defaultRemote=origin checkout master
          git merge --ff-only upstream/master
          git -c checkout.defaultRemote=origin checkout more-branches
          git rebase master -v
          
      - name: Sync weekly
        if: steps.remotes.outputs.weekly >= 0
        run: git branch -vf weekly upstream/nixpkgs-unstable
        
      - name: Sync monthly
        if: steps.remotes.outputs.monthly >= 0
        run: git branch -vf weekly upstream/nixpkgs-unstable
    
      - name: Push changes
        run: git push --all origin
        
      
